### ISSUE TITLE
Incorrect element type of arrays

### ISSUE THREAD

**Issue by mewmew** [Predelnik/Scripture#14]
The type of [items](http://sanctuary.github.io/notes/#variable/items) is listed by Scripture as ` int  [128]`, but should be ` Item  [128]`. The same is true for [players](http://sanctuary.github.io/notes/#variable/players).

As far as I can tell, everything worked perfectly when merging sanctuary/notes#250. The structure definitions are still parsed correctly, the enums are cross-referenced, the link to the GitHub source code works. So, Scripture seems to be build to be a very general documentation generation tool, as every file moved it's location, and the documentation generation still works.

Is the issue with element types something new, or was this working correctly before sanctuary/notes#250?

**Comment by Predelnik** [comment]
It looks like `-I$notes_path` in `extract.sh` should be changed `-I$notes_path/include` now. Is this correct?

**Comment by mewmew** [comment]
Ah, that might be it. I'll have a look.

**Comment by mewmew** [comment]
Verified that it's working again the merge: http://sanctuary.github.io/notes/#variable/items
