### ISSUE TITLE
Output compiler warnings and errors

### ISSUE THREAD

**Issue by mewmew** [Predelnik/Scripture#16]
It would be very useful if Scripture output warnings when unable to locate a type (or some other compile error or warning occurs).

For instance, this would make it easy to spot issues such as those reported in #14. For reference, the log on Travis for that build did not output any warnings. https://travis-ci.org/sanctuary/notes/builds/373796038#L767

**EDIT:** one benefit of this would be to add even further cross-validations that the contents of the notes repo is correct. We have Scripture, clang, and CFFI from Python all of which parse the C source code and may report issues.

**Comment by Predelnik** [comment]
This is how it should look now for issue in #14. Not the prettiest error reporting but hopefully it's enough.
![image](https://user-images.githubusercontent.com/2133957/39525233-17e5925a-4e24-11e8-84db-742ea75715f3.png)
Optionally some warnings could be added to clang arguments if it may help.

**Comment by mewmew** [comment]
Perfect! Does Scripture return a non-zero status code when reporting warnings (or errors)?

**Comment by Predelnik** [comment]
I think it should since it just raises uncaught python exception

**Comment by mewmew** [comment]
Great

**Comment by mewmew** [comment]
Verified that it works as intended.

https://travis-ci.org/sanctuary/notes/builds/373799210#L772 reports a build error, with:
```
'stdarg.h' file not found at <SourceLocation file '/home/travis/build/sanctuary/notes/include/typedefs.h', line 5, column 10>
```

Good job :)
