### ISSUE TITLE
Feature request: permanent links to address notes/#address/0xAAAAAA

### ISSUE THREAD

**Issue by mewmew** [Predelnik/Scripture#5]
It would be great to add `notes/#address/0xAAAAAA` or something along those links to reference functions and global variables by address rather than name. The main benefit of this is that names are likely to change as we continue to gain new understanding, and continue to refine and improve the notes over time.

Thus the address is a way to get permanent links, so that we can try to consistently used those for cross-references and discussions; so links don't go stale.

For instance, I'd like to refer to http://sanctuary.github.io/notes/#function/trigs_init_warps_town as http://sanctuary.github.io/notes/#address/0x4619B6

**Comment by Predelnik** [comment]
Yes that's the good idea. I wonder if I should keep links by name also though or discard them in the favor of addresses altogether.

**Comment by Predelnik** [comment]
So for now I supported it as an additional way to link to functions/variables with the exact syntax you propose.
Additionaly I made addresses in description as links in that style so they could be easily copied to be used as reference:
![image](https://user-images.githubusercontent.com/2133957/36339414-f1b17708-13d5-11e8-942f-80eb0ab2d918.png)

**Comment by mewmew** [comment]
That's great! Thanks!
